### ISSUE TITLE
Create/edit basic UI for users

### ISSUE THREAD

**Issue by michalmrowiec** [michalmrowiec/CarRental#1]
- Create home page (nav bar, )
- Login window (email, password)
- Registration window (name, last name, email, password, repeat password)

**Comment by michalmrowiec** [comment]
Registration window is intended for customers only.
Login window is common to customers and employees.

**Comment by marcinkusnierz91** [comment]
ziomek, to poniżej trzeba porozbijać na oddzielne taski
Create home page (nav bar, )
Login window (email, password)
Registration window (name, last name, email, password, repeat password)

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
gethup, @YSShannon, @sdrawkab, @stftaruna, @karanveersp, @Viktor879, @novalis78, @WonkySoft, @hyk1255, @tonerdo, @StephanSalas, @ciceroche, @Bilual, @yasarmuh, @thebitbrine, @vahbuna, @hvgmbdmg, @crackevil, @jacks0n, @whiitly, @Pouria-Meftahi, @theangelsofwar, @markcheno, @StanislavBerezin, @sbusso, @matteoettam09, @samchaaa, @tamezarnold, @lz92at, @logikinc, @franciscomoloureiro, @simonpucher, @callmecorra, @danlinenberg, @huangjiajunk, @douglasrocha, @tom821017, @tahoedesigner, @mraoufat, @rcgalbo, @mattz0rt, @tactools, @shaoning, @jingxi1, @DerekChia, @guanyc, @trgerinner, @aerooooo, @mitagmio, @ilizane
